baseURL = "https://yudiwdynto.github.io/blog/"
title = "yudiwdynto"

theme = "hugo-coder"

languageCode = "en"
defaultContentLanguage = "en"

paginate = 20

pygmentsStyle = "monokai"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params]
author = "Yudi Widiyanto"
description = "Yudi Widiyanto personal website"
info = "Sebuah personal blog"
keywords = "blog,personal"
avatarURL = "images/avatar.png"
dateFormat = "January 2, 2006"
hideFooter = false

colorScheme = "auto"
hideColorSchemeToggle = true
maxSeeAlsoItems = 5
enableTwemoji = false

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Twitter"
icon = "fa fa-twitter"
weight = 1
url = "https://twitter.com/yudiwdynto/"

[[params.social]]
name = "Telegram"
icon = "fa fa-telegram"
weight = 2
url = "https://t.me/yudiwdynto/"

[[menu.main]]
name = "Posts"
weight = 1
url = "posts/"


